version: "3.8"
#limits sprawdź
#logging
#labels
#cap_add and cap_rm

#prawdopodobnie tylko manager dla database i redisa
#dodać migrate do obrazu
services:
  web:
    container_name: web-container
    image: localhost:5000/web:1.0.1
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - worker
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1
    networks:
      app-network:
        aliases:
          - web
          - webserver

  redis:
    container_name: redis
    image: redis
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1
    networks:
      app-network:
        aliases:
          - redis

  postgres:
    container_name: postgres
    image: postgres
    deploy:
      placement:
        max_replicas_per_node: 1
      mode: global
    networks:
      app-network:
        aliases:
          - postgres
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=pguser

  celery:
    container_name: celery-worker
    image: localhost:5000/worker:1.0.1
    deploy:
      replicas: 4
      placement:
        max_replicas_per_node: 2
    networks:
      app-network:
        aliases:
          - worker
          
networks:
  app-network:
    driver: overlay
    driver_opts:
      encrypted: "true" 
volumes:
  pgdata:
    external: true
    name: pgdata
