version: "3.8"
#limits sprawdź
#logging
#labels
#cap_add and cap_rm
#healthcheck

#prawdopodobnie tylko manager dla database i redisa
#dodać migrate do obrazu
services:
  web:
    image: ghcr.io/mporada259449/web:1.2.4
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - worker
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 2
        constraints:
          - "node.role==worker"
      restart_policy:
        condition: on-failure
        delay: 15s
        window: 60s
      resources:
        limits: 
          cpus: '0.25'
          memory: 500m
    networks:
      app-network:
        aliases:
          - web
          - webserver
    secrets:
      - DBHOST
      - DBNAME
      - DBPASSWORD
      - DBPORT 
      - DBUSER
      - DJANGO_SECRET_KEY
      - DJANGO_SUPERUSER_PASSWORD
    cap_drop:
      - CHOWN
      - DAC_OVERRIDE
      - SYS_CHROOT
      - NET_BIND_SERVICE
      - NET_ADMIN
      - SYS_MODULE
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "5"

    #healthcheck:
    #  test: ["CMD", "curl", "-f", "http://web"]
    #  interval: 

  redis:
    image: redis@sha256:a954691db2c951a2b0e5de460e154e8bf3ce466c8903d4acb84a15081b38769b
    ports: 
      - "6379:6379"
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==manager"
      restart_policy:
        condition: on-failure
        window: 60s
        delay: 5s
      resources:
        limits: 
          cpus: '0.25'
          memory: 500m
    networks:
      app-network:
        aliases:
          - redis
    cap_drop:
      - CHOWN
      - DAC_OVERRIDE
      - SYS_CHROOT
      - NET_BIND_SERVICE
      - NET_ADMIN
      - SYS_MODULE
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "5"

  postgres:
    image: postgres:postgres@sha256:8b4e94a052578fa74b12b783ed633fb93c96bc6a87906ecf6b4a25382d94afcc
    ports: 
      - "5432:5432"
    deploy:
      placement:
        max_replicas_per_node: 1
        constraints:
        - "node.role==manager"
      mode: global
      restart_policy:
        condition: on-failure
        window: 60s
        delay: 5s
      resources:
        limits: 
          cpus: '0.25'
          memory: 500m
    networks:
      app-network:
        aliases:
          - postgres
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/DBPASSWORD
      - POSTGRES_USER_FILE=/run/secrets/DBUSER
      - POSTGRES_DB_FILE=/run/secrets/DBNAME
    secrets:
      - DBUSER
      - DBNAME
      - DBPASSWORD
    cap_drop:
      - SYS_CHROOT
      - NET_BIND_SERVICE
      - NET_ADMIN
      - SYS_MODULE
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "5"

  celery:
    depends_on:
      - redis
      - postgres
    image: ghcr.io/mporada259449/worker:1.2.3
    deploy:
      replicas: 4
      placement:
        max_replicas_per_node: 2
        constraints:
          - "node.role==worker"
      restart_policy:
        condition: on-failure
        delay: 15s
        window: 60s
      resources:
        limits: 
          cpus: '0.25'
          memory: 500m
    networks:
      app-network:
        aliases:
          - worker
          - celery-worker
    secrets:
      - DBHOST
      - DBNAME
      - DBPASSWORD
      - DBPORT 
      - DBUSER
      - DJANGO_SECRET_KEY
    cap_drop:
      - CHOWN
      - DAC_OVERRIDE
      - SYS_CHROOT
      - NET_BIND_SERVICE
      - NET_ADMIN
      - SYS_MODULE
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "5"
          
networks:
  app-network:
    driver: overlay
    attachable: true
#    driver_opts:
#      encrypted: "true" 
volumes:
  pgdata:
    external: true
    name: pgdata
secrets:
  DBHOST:
    external: true
  DBPORT:
    external: true
  DBPASSWORD:
    external: true
  DBUSER:
    external: true
  DBNAME:
    external: true
  DJANGO_SECRET_KEY:
    external: true
  DJANGO_SUPERUSER_PASSWORD:
    external: true
