version: "3.8"
#limits sprawdź
#logging
#labels
#cap_add and cap_rm
#healthcheck

#prawdopodobnie tylko manager dla database i redisa
#dodać migrate do obrazu
services:
  web:
    container_name: web-container
    image: ghcr.io/mporada259449/web:1.2.2
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - worker
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1
    networks:
      app-network:
        aliases:
          - web
          - webserver
    secrets:
      - DBHOST
      - DBNAME
      - DBPASSWORD
      - DBPORT 
      - DBUSER
      - DJANGO_SECRET_KEY
      - DJANGO_SUPERUSER_PASSWORD
    #healthcheck:
    #  test: ["CMD", "curl", "-f", "http://web"]
    #  interval: 

  redis:
    container_name: redis
    image: redis
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==manager"
      restart_policy:
        condition: on-failure
        window: 60s
        delay: 5s
    networks:
      app-network:
        aliases:
          - redis

  postgres:
    container_name: postgres
    image: postgres
    deploy:
      placement:
        max_replicas_per_node: 1
        constraints:
        - "node.role==manager"
      mode: global
      restart_policy:
        condition: on-failure
        window: 60s
        delay: 5s
    networks:
      app-network:
        aliases:
          - postgres
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/DBPASSWORD
      - POSTGRES_USER_FILE=/run/secrets/DBUSER
      - POSTGRES_DB_FILE=/run/secrets/DBNAME
    secrets:
      - DBUSER
      - DBNAME
      - DBPASSWORD

  celery:
    container_name: celery-worker
    depends_on:
      - redis
      - postgres
    image: ghcr.io/mporada259449/worker:1.1.1
    deploy:
      replicas: 4
      placement:
        max_replicas_per_node: 2
    networks:
      app-network:
        aliases:
          - worker
    secrets:
      - DBHOST
      - DBNAME
      - DBPASSWORD
      - DBPORT 
      - DBUSER
      - DJANGO_SECRET_KEY
          
networks:
  app-network:
    driver: overlay
    driver_opts:
      encrypted: "true" 
volumes:
  pgdata:
    external: true
    name: pgdata
secrets:
  DBHOST:
    external: true
  DBPORT:
    external: true
  DBPASSWORD:
    external: true
  DBUSER:
    external: true
  DBNAME:
    external: true
  DJANGO_SECRET_KEY:
    external: true
  DJANGO_SUPERUSER_PASSWORD:
    external: true